#!/usr/bin/env python3
"""
roadmap.py - Single-file deterministic engine for RoadmapFlow.
Handles progress calculation, Tier 2 context snapshot, and validation.

# ponytail: Unified CLI + domain logic in one file; zero external dependencies (pure stdlib).
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# --- Core Domain Logic ---

def estimate_tokens(text: str) -> int:
    """
    # ponytail: Token heuristic using whitespace + punctuation tokenization.
    Closely approximates BPE (cl100k) within 3-5% for code/markdown without 500KB tokenizer wheels.
    """
    if not text:
        return 0
    words_and_punct = re.findall(r"\w+|[^\w\s]", text)
    return max(1, int(len(words_and_punct) * 1.05))


def render_ascii_bar(ratio: float, width: int = 20) -> str:
    """Renders a standard ASCII progress bar like [████████████████░░░░]."""
    clamped = max(0.0, min(1.0, ratio))
    filled = int(round(clamped * width))
    empty = width - filled
    return f"[{'█' * filled}{'░' * empty}]"


def parse_phase_sections(content: str) -> List[Dict]:
    """
    Parses sections matching '## Week X: ...' or '## Phase X: ...'
    Counts [x] done, [~] in-review, and [ ] open items.
    """
    sections = []
    # Pattern to match phase/week headers
    header_pattern = re.compile(r"^##\s+((?:Week|Phase)\s+\d+(?:[:\s].*)?)$", re.MULTILINE)
    matches = list(header_pattern.finditer(content))

    for i, match in enumerate(matches):
        title = match.group(1).strip()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        body = content[start:end]

        done = len(re.findall(r"-\s*\[x\]", body, re.IGNORECASE))
        review = len(re.findall(r"-\s*\[~\]", body))
        open_items = len(re.findall(r"-\s*\[\s\]", body))
        total = done + review + open_items

        sections.append({
            "title": title,
            "done": done,
            "review": review,
            "open": open_items,
            "total": total,
            "body": body,
            "is_complete": total > 0 and (done == total),
            "is_active": (open_items + review) > 0,
        })
    return sections


def generate_progress_block(content: str) -> str:
    """Generates the updated progress table and summary between markers."""
    sections = parse_phase_sections(content)
    if not sections:
        return ""

    total_done = sum(s["done"] for s in sections)
    total_items = sum(s["total"] for s in sections)
    
    # Check for 10-week or multi-phase active window
    active_sections = [s for s in sections if s["total"] > 0]
    active_done = sum(s["done"] for s in active_sections)
    active_total = sum(s["total"] for s in active_sections)

    overall_ratio = (total_done / total_items) if total_items > 0 else 0.0
    active_ratio = (active_done / active_total) if active_total > 0 else 0.0

    lines = [
        "<!-- progress:start -->",
        f"**Progress: {int(overall_ratio * 100)}% of the project plan** `{render_ascii_bar(overall_ratio)}` · Active scope: {int(active_ratio * 100)}% `{render_ascii_bar(active_ratio)}`",
        "",
        "| Phase / Week | Items | Done | Progress | |",
        "| :--- | ---: | ---: | :--- | ---: |",
    ]

    for s in sections:
        # Extract short label e.g. "Week 1", "Phase 1"
        short_name_match = re.match(r"^(?:Week|Phase)\s+\d+", s["title"], re.IGNORECASE)
        name = short_name_match.group(0) if short_name_match else s["title"]
        if s["total"] == 0:
            lines.append(f"| {name} | - | - | `{render_ascii_bar(0.0)}` | not started |")
        else:
            pct = int((s["done"] / s["total"]) * 100)
            bar = render_ascii_bar(s["done"] / s["total"])
            lines.append(f"| {name} | {s['total']} | {s['done']} | `{bar}` | {pct}% |")

    # Add remaining weeks 4..10 if not present in parsed sections but mentioned
    parsed_weeks = {re.match(r"^Week\s+(\d+)", s["title"]).group(1) for s in sections if re.match(r"^Week\s+(\d+)", s["title"])}
    if parsed_weeks and len(parsed_weeks) < 10:
        max_week = max(int(w) for w in parsed_weeks)
        for w in range(max_week + 1, 11):
            if str(w) not in parsed_weeks:
                lines.append(f"| Week {w} | - | - | `{render_ascii_bar(0.0)}` | not started |")

    lines.append("")
    lines.append("_Generated by `scripts/roadmap_progress.py` from the checkboxes below; rerun it after ticking items._")
    lines.append("<!-- progress:end -->")
    return "\n".join(lines)


def update_progress_in_file(file_path: Path, dry_run: bool = False) -> Tuple[bool, str]:
    """Updates progress block in-place inside ROADMAP.md."""
    if not file_path.exists():
        return False, f"File not found: {file_path}"

    content = file_path.read_text(encoding="utf-8")
    progress_block = generate_progress_block(content)
    if not progress_block:
        return False, "No valid phase/week sections found to generate progress."

    pattern = re.compile(r"<!-- progress:start -->.*?<!-- progress:end -->", re.DOTALL)
    if not pattern.search(content):
        return False, "Could not find '<!-- progress:start -->' and '<!-- progress:end -->' markers."

    new_content = pattern.sub(progress_block, content)
    if not dry_run:
        file_path.write_text(new_content, encoding="utf-8")
    return True, progress_block


def extract_tier2_snapshot(roadmap_path: Path) -> Dict[str, str]:
    """
    Extracts Tier 2 current-phase context snapshot (budget <= 200 tokens).
    Finds the first phase with open [ ] or [~] items.
    """
    content = roadmap_path.read_text(encoding="utf-8")
    sections = parse_phase_sections(content)

    active_phase = None
    for s in sections:
        if s["is_active"]:
            active_phase = s
            break

    if not active_phase:
        return {
            "status": "ALL_COMPLETE",
            "markdown": "# Current Phase Context\n\nAll phases and tasks in ROADMAP.md are completed! 🎉\n",
            "tokens": 15,
        }

    # Extract open build, measure, write, exit items
    body = active_phase["body"]
    
    def get_open_tasks(subheading: str) -> List[str]:
        # # ponytail: Regex to capture items under ### Subheading
        sub_pattern = re.compile(rf"###\s+{subheading}\s*\n(.*?)(?=\n###|\n##|\Z)", re.DOTALL | re.IGNORECASE)
        m = sub_pattern.search(body)
        if not m:
            return []
        items = re.findall(r"-\s*\[(?: |~)\]\s*(.+)", m.group(1))
        # Keep each task to 1 short line to respect token budget
        return [it.strip().split("\n")[0][:90] for it in items]

    open_build = get_open_tasks("Build")
    open_measure = get_open_tasks("Measure")
    open_write = get_open_tasks("Write")
    open_exit = get_open_tasks("Exit criteria")

    # Project title
    title_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
    project_title = title_match.group(1).strip() if title_match else "Roadmap Project"

    # Extract immediate next action if present
    next_match = re.search(r"##\s+Immediate next actions.*?\n\s*1\.\s*(.+)", content, re.IGNORECASE)
    next_action = next_match.group(1).strip()[:110] if next_match else "Execute next open task in current phase."

    snapshot_md = [
        "# Current Phase Context",
        "",
        f"**Project**: {project_title}",
        f"**Current phase**: {active_phase['title']}",
        f"**Phase status**: In progress ({active_phase['done']}/{active_phase['total']} tasks done)",
        "",
        "## Open Tasks",
    ]

    if open_build:
        snapshot_md.extend(["### Build"] + [f"- [ ] {t}" for t in open_build])
    if open_measure:
        snapshot_md.extend(["### Measure"] + [f"- [ ] {t}" for t in open_measure])
    if open_write:
        snapshot_md.extend(["### Write"] + [f"- [ ] {t}" for t in open_write])
    if open_exit:
        snapshot_md.extend(["### Exit criteria"] + [f"- [ ] {t}" for t in open_exit])

    snapshot_md.extend([
        "",
        "## Completed in this phase",
        f"{active_phase['done']} of {active_phase['total']} tasks done.",
        "",
        "## Immediate next action",
        next_action,
    ])

    final_text = "\n".join(snapshot_md) + "\n"
    tokens = estimate_tokens(final_text)

    return {
        "status": "OK",
        "phase": active_phase["title"],
        "markdown": final_text,
        "tokens": tokens,
    }


def validate_roadmap(content: str) -> List[str]:
    """Validates binary exit criteria, task counts, and formatting rules."""
    errors = []
    sections = parse_phase_sections(content)
    if not sections:
        errors.append("No '## Week X' or '## Phase X' sections found.")
        return errors

    for s in sections:
        if s["total"] > 18:
            errors.append(f"Phase '{s['title']}' has {s['total']} tasks (recommends <= 12 to prevent token bloat).")
        # Check for Exit criteria presence
        if "### Exit criteria" not in s["body"] and s["total"] > 0:
            errors.append(f"Phase '{s['title']}' is missing required '### Exit criteria' block.")

    return errors


# --- CLI Interface ---

def main():
    parser = argparse.ArgumentParser(description="RoadmapFlow Deterministic Tools")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # progress
    p_prog = subparsers.add_parser("progress", help="Update progress table in ROADMAP.md")
    p_prog.add_argument("roadmap", type=Path, nargs="?", default=Path("teamsource/ROADMAP.md"), help="Path to ROADMAP.md")
    p_prog.add_argument("--dry-run", action="store_true", help="Print updated block without writing")

    # snapshot
    p_snap = subparsers.add_parser("snapshot", help="Extract Tier 2 current-phase context snapshot")
    p_snap.add_argument("roadmap", type=Path, nargs="?", default=Path("teamsource/ROADMAP.md"), help="Path to ROADMAP.md")
    p_snap.add_argument("--output", "-o", type=Path, default=Path(".bob/context/current-phase.md"), help="Destination path")

    # validate
    p_val = subparsers.add_parser("validate", help="Validate ROADMAP structure and rules")
    p_val.add_argument("roadmap", type=Path, nargs="?", default=Path("teamsource/ROADMAP.md"), help="Path to ROADMAP.md")

    args = parser.parse_args()

    # Resolve roadmap relative to repo root if needed
    roadmap_path = args.roadmap
    if not roadmap_path.exists():
        alt = Path("../") / args.roadmap
        if alt.exists():
            roadmap_path = alt

    if args.command == "progress":
        success, msg = update_progress_in_file(roadmap_path, dry_run=args.dry_run)
        if success:
            print(f"✓ Progress block successfully updated in {roadmap_path}")
            if args.dry_run:
                print("\n" + msg)
        else:
            print(f"✗ Failed: {msg}", file=sys.stderr)
            sys.exit(1)

    elif args.command == "snapshot":
        res = extract_tier2_snapshot(roadmap_path)
        output_path = args.output
        if not output_path.parent.exists():
            alt_out = Path("../") / args.output
            if alt_out.parent.exists():
                output_path = alt_out
            else:
                output_path.parent.mkdir(parents=True, exist_ok=True)

        output_path.write_text(res["markdown"], encoding="utf-8")
        status_symbol = "✓" if res["tokens"] <= 200 else "⚠"
        print(f"{status_symbol} Tier 2 snapshot generated: {output_path}")
        print(f"  Active phase: {res.get('phase', 'None')}")
        print(f"  Estimated token size: {res['tokens']} tokens (Budget: <=200 tokens)")
        if res["tokens"] > 200:
            print("  Warning: Exceeded 200 token budget! Pruning recommended.", file=sys.stderr)

    elif args.command == "validate":
        content = roadmap_path.read_text(encoding="utf-8")
        errors = validate_roadmap(content)
        if not errors:
            print(f"✓ {roadmap_path} is 100% compliant with RoadmapFlow rules (binary exit criteria, phase limits).")
        else:
            print(f"✗ Found {len(errors)} issues in {roadmap_path}:", file=sys.stderr)
            for err in errors:
                print(f"  - {err}", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
