#!/usr/bin/env python3
"""
scaffold.py - Project Scaffolder and Standard Layout Auditor for RoadmapFlow.
Generates and audits standard 3-tier folder structures for any project using RoadmapFlow.

# ponytail: Zero-dependency stdlib script; generates full standard tree or audits compliance in one file.
"""

import argparse
import sys
from datetime import date
from pathlib import Path
from typing import Dict, List, Tuple

from roadmap import estimate_tokens, render_ascii_bar


# --- Templates conforming to RoadmapFlow standards ---

def get_plan_template(name: str, stack: str, phases: int) -> str:
    today = date.today().isoformat()
    lines = [
        f"# Project Plan: {name}",
        "",
        "> Static master plan. Edit to refine the plan; never edit to record progress — use ROADMAP.md.",
        "",
        "## Overview",
        f"- Goal: Build and ship {name}",
        f"- Stack: {stack}",
        "- Deliverables: Production-ready codebase, tests, and documentation",
        f"- Timeline: {phases} phases",
        "- Team: Core Engineering",
        "",
        "## Decisions Log",
        "| Topic | Option A | Option B | Decision | Reason |",
        "| :--- | :--- | :--- | :--- | :--- |",
        f"| Architecture | Monolith | Microservices | Modular monolith | Minimal operational overhead |",
        "",
    ]

    for p in range(1, phases + 1):
        lines.extend([
            f"## Phase {p}: {'Foundation & Infrastructure' if p == 1 else f'Feature Module {p}'}",
            "### Build",
            f"- [ ] Core skeleton for Phase {p} in `src/`",
            f"- [ ] Module implementation and interfaces",
            "### Measure",
            f"- [ ] Automated unit tests in `tests/test_phase_{p}.py`",
            "### Write",
            f"- [ ] Architecture notes in `docs/phase_{p}.md`",
            "### Exit criteria",
            "- [ ] All phase unit tests pass with zero regressions",
            "",
        ])

    lines.extend([
        "## Risks and Fallbacks",
        "| Risk | Signal | Fallback |",
        "| :--- | :--- | :--- |",
        "| Scope creep | Phase has > 8 tasks | Split phase into sub-phases |",
        "",
    ])
    return "\n".join(lines)


def get_roadmap_template(name: str, phases: int) -> str:
    today = date.today().isoformat()
    bar_empty = render_ascii_bar(0.0)
    lines = [
        f"# Roadmap and Status — {name}",
        "",
        "Master plan: `PLAN.md`. This file is the live status board.",
        "**Rule: tick items here in the same commit as the work. Never edit PLAN.md to record progress.**",
        "",
        "Legend: `[x]` done · `[~]` written but not verified · `[ ]` open",
        "",
        f"Last updated: {today}",
        "",
        "## Progress",
        "",
        "<!-- progress:start -->",
        f"**Progress: 0% of the project plan** `{bar_empty}` · Active scope: 0% `{bar_empty}`",
        "",
        "| Phase / Week | Items | Done | Progress | |",
        "| :--- | ---: | ---: | :--- | ---: |",
    ]

    for p in range(1, phases + 1):
        lines.append(f"| Phase {p} | 4 | 0 | `{bar_empty}` | not started |")

    lines.extend([
        "",
        "_Generated by `scripts/roadmap_progress.py` from the checkboxes below; rerun it after ticking items._",
        "<!-- progress:end -->",
        "",
        "---",
        "",
    ])

    for p in range(1, phases + 1):
        lines.extend([
            f"## Phase {p}: {'Foundation & Infrastructure' if p == 1 else f'Feature Module {p}'}",
            "",
            "### Build",
            f"- [ ] Core skeleton for Phase {p} in `src/`",
            f"- [ ] Module implementation and interfaces",
            "",
            "### Measure",
            f"- [ ] Automated unit tests in `tests/test_phase_{p}.py`",
            "",
            "### Write",
            f"- [ ] Architecture notes in `docs/phase_{p}.md`",
            "",
            "### Exit criteria",
            "- [ ] All phase unit tests pass with zero regressions",
            "",
            "---",
            "",
        ])

    lines.extend([
        "## Immediate next actions (in order)",
        f"1. Setup repository structure and execute Phase 1 Build tasks.",
        "2. Implement tests and verify exit criteria.",
        "",
        "## Change log",
        f"- {today}: Initial plan and roadmap generated by RoadmapFlow.",
        "",
    ])
    return "\n".join(lines)


def get_architecture_template(name: str, stack: str) -> str:
    today = date.today().isoformat()
    return f"""# Architecture Snapshot — {name}

> Tier 1 context: always load this file at session start. Target size: ≤ 500 tokens.
> Last updated: {today}

## What this project is
High-performance system for {name}. Produces deterministic execution, verifiable milestones, and clean code.

## Stack
- Language/runtime: {stack}
- Architecture: Modular, test-driven, 3-tier context management

## Key Decisions
- Strict 3-Tier Context: Tier 1 (always in context) + Tier 2 (session snapshot) to avoid LLM context bloat.
- Binary Exit Criteria: Every phase must pass objective exit verification before moving to next phase.

## Source Layout
- `src/`: Core implementation modules
- `tests/`: Automated unit & integration tests
- `docs/`: Technical specifications and reports
- `scripts/`: Operational tools and progress hooks
- `.bob/context/`: Tier 1 (`architecture.md`) and Tier 2 (`current-phase.md`)

## What NOT to re-read every session
- `PLAN.md`: Full multi-phase plan (static archive — query via subagent)
- `ROADMAP.md`: Completed phases history (use `.bob/context/current-phase.md` instead)
"""


def get_gitignore_template() -> str:
    return """# Environments & dependencies
__pycache__/
*.py[cod]
node_modules/
venv/
.env
.env.*
credentials.json
ibm-credentials.env
*.key
*.pem

# RoadmapFlow Local Session Snapshot (Tier 2 local state - do NOT commit)
.bob/context/current-phase.md

# Build & OS
.DS_Store
dist/
build/
"""


def get_bobignore_template() -> str:
    return """# Prevent AI agents from reading sensitive credentials or large build caches
.env
.env.*
credentials.json
ibm-credentials.env
*.key
*.pem
node_modules/
venv/
dist/
build/
"""


# --- Scaffolding & Auditing Logic ---

def scaffold_standard_project(target_dir: Path, name: str, stack: str, phases: int) -> List[str]:
    """Generates the full standard RoadmapFlow project directory structure."""
    created = []

    # Directories
    dirs = [
        target_dir / "src",
        target_dir / "tests",
        target_dir / "docs",
        target_dir / "scripts",
        target_dir / ".bob/context",
        target_dir / ".bob/rules-agent",
        target_dir / ".bob/rules-ask",
        target_dir / ".bob/rules-plan",
    ]
    for d in dirs:
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            created.append(f"dir:  {d.relative_to(target_dir)}")

    # Files
    file_map = {
        target_dir / "PLAN.md": get_plan_template(name, stack, phases),
        target_dir / "ROADMAP.md": get_roadmap_template(name, phases),
        target_dir / ".bob/context/architecture.md": get_architecture_template(name, stack),
        target_dir / ".gitignore": get_gitignore_template(),
        target_dir / ".bobignore": get_bobignore_template(),
        target_dir / "src/README.md": f"# Source Code — {name}\n\nProject modules live here.\n",
        target_dir / "tests/README.md": f"# Test Suite — {name}\n\nAutomated tests live here.\n",
    }

    for p, content in file_map.items():
        if not p.exists():
            p.write_text(content, encoding="utf-8")
            created.append(f"file: {p.relative_to(target_dir)}")

    # Generate initial Tier 2 current-phase.md
    from roadmap import extract_tier2_snapshot
    res = extract_tier2_snapshot(target_dir / "ROADMAP.md")
    tier2_path = target_dir / ".bob/context/current-phase.md"
    tier2_path.write_text(res["markdown"], encoding="utf-8")
    created.append(f"file: {tier2_path.relative_to(target_dir)} (Tier 2 snapshot: {res['tokens']} tokens)")

    # Scripts runner
    script_runner = target_dir / "scripts/roadmap_progress.py"
    if not script_runner.exists():
        script_code = """#!/usr/bin/env python3
import sys
from pathlib import Path
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "things"))
from roadmap import update_progress_in_file
if __name__ == "__main__":
    success, msg = update_progress_in_file(REPO_ROOT / "ROADMAP.md")
    print(msg if success else f"Error: {msg}", file=sys.stdout if success else sys.stderr)
"""
        script_runner.write_text(script_code, encoding="utf-8")
        script_runner.chmod(0o755)
        created.append(f"file: {script_runner.relative_to(target_dir)}")

    return created


def audit_standard_project(target_dir: Path) -> Tuple[bool, List[str]]:
    """Audits an existing directory against RoadmapFlow standards."""
    reports = []
    is_compliant = True

    def check(condition: bool, pass_msg: str, fail_msg: str):
        nonlocal is_compliant
        if condition:
            reports.append(f"  [PASS] {pass_msg}")
        else:
            is_compliant = False
            reports.append(f"  [FAIL] {fail_msg}")

    # 1. Structure check
    check((target_dir / "PLAN.md").exists(), "PLAN.md exists (Master Plan)", "Missing PLAN.md")
    check((target_dir / "ROADMAP.md").exists(), "ROADMAP.md exists (Live Status Board)", "Missing ROADMAP.md")
    check((target_dir / ".gitignore").exists(), ".gitignore exists", "Missing .gitignore")
    check((target_dir / ".bobignore").exists(), ".bobignore exists", "Missing .bobignore")

    # 2. Tier 1 Anchor check
    tier1 = target_dir / ".bob/context/architecture.md"
    if tier1.exists():
        tokens = estimate_tokens(tier1.read_text(encoding="utf-8"))
        check(tokens <= 650, f"Tier 1 architecture.md size: {tokens} tokens (Target ≤ 500-650)", f"Tier 1 architecture.md exceeds budget: {tokens} tokens")
    else:
        check(False, "", "Missing Tier 1 anchor: .bob/context/architecture.md")

    # 3. Tier 2 Snapshot check
    tier2 = target_dir / ".bob/context/current-phase.md"
    if tier2.exists():
        tokens = estimate_tokens(tier2.read_text(encoding="utf-8"))
        check(tokens <= 200, f"Tier 2 current-phase.md size: {tokens} tokens (Budget ≤ 200)", f"Tier 2 current-phase.md exceeds 200 tokens: {tokens} tokens")
    else:
        check(False, "", "Missing Tier 2 snapshot: .bob/context/current-phase.md (run /roadmap-navigator)")

    # 4. Check gitignore safety for Tier 2
    gitignore = target_dir / ".gitignore"
    if gitignore.exists():
        git_text = gitignore.read_text(encoding="utf-8")
        check(".bob/context/current-phase.md" in git_text, ".gitignore properly excludes local Tier 2 session snapshot", ".gitignore fails to exclude .bob/context/current-phase.md")

    # 5. Core directories
    for d in ["src", "tests", "docs", "scripts"]:
        check((target_dir / d).is_dir(), f"Standard directory `{d}/` exists", f"Missing standard directory `{d}/`")

    return is_compliant, reports


# --- CLI Interface ---

def main():
    parser = argparse.ArgumentParser(description="RoadmapFlow Standard Folder Scaffolder & Auditor")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # init
    p_init = subparsers.add_parser("init", help="Scaffold standard RoadmapFlow project folders")
    p_init.add_argument("target", type=Path, nargs="?", default=Path("."), help="Target directory")
    p_init.add_argument("--name", default="RoadmapProject", help="Project name")
    p_init.add_argument("--stack", default="Python 3.11+", help="Technology stack")
    p_init.add_argument("--phases", type=int, default=4, help="Number of phases (default: 4)")

    # audit
    p_audit = subparsers.add_parser("audit", help="Audit repository against RoadmapFlow standards")
    p_audit.add_argument("target", type=Path, nargs="?", default=Path("."), help="Directory to audit")

    args = parser.parse_args()

    if args.command == "init":
        target = args.target.resolve()
        print(f"Scaffolding RoadmapFlow standard layout in: {target}")
        created = scaffold_standard_project(target, args.name, args.stack, args.phases)
        for c in created:
            print(f"  + {c}")
        print(f"\n✓ Successfully initialized {args.name}! Ready for `/roadmap-navigator` and `/dev-workflow`.")

    elif args.command == "audit":
        target = args.target.resolve()
        # If in 'things/', default to parent repo
        if not (target / "ROADMAP.md").exists() and (target / "../teamsource/ROADMAP.md").exists():
            target = (target / "..").resolve()

        print(f"Auditing RoadmapFlow standards in: {target}\n")
        compliant, reports = audit_standard_project(target)
        for r in reports:
            print(r)
        print("\n" + ("✓ COMPLIANT: Repository meets RoadmapFlow standards!" if compliant else "✗ NON-COMPLIANT: Fix issues marked [FAIL]."))
        if not compliant:
            sys.exit(1)


if __name__ == "__main__":
    main()
